import "../globals.css";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen">
          <div className="w-80 bg-red-200"></div>
          <div className="flex bg-yellow-500 flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
